import 'babel-polyfill';
import React from 'react';
import ReactDOM from 'react-dom';

require('../styles/style.scss');

ReactDOM.render(
  <h2>Welcome to the Boilerplate for Redux-React generated by Divesh Panwar</h2>,
  document.getElementById('root')
);
